name: otp
version: 3.1.0
description: RFC6238 Time-Based One-Time Password / Google Authenticator Library
homepage: https://github.com/Daegalus/dart-otp
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  base32: ^2.1.3
  crypto: ^3.0.0
  logging: ^1.0.2
dev_dependencies:
  lints: ^1.0.1
  test: ^1.21.2