name: otp
version: 3.0.2
description: RFC6238 Time-Based One-Time Password / Google Authenticator Library
homepage: https://github.com/Daegalus/dart-otp
environment:
  sdk: ">=2.12.0-0 <3.0.0"
dependencies:
  base32: ^2.0.0
  crypto: ^3.0.1
  logging: ^1.0.1
dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.5