name: otp
version: 1.0.3
author: Yulian Kuncheff <yulian@kuncheff.com>
description: RFC6238 Time-Based One-Time Password / Google Authenticator Library
homepage: https://github.com/Daegalus/dart-otp
environment:
  sdk: ">=1.13.0 <3.0.0"
dependencies:
  pointycastle: ^1.0.1
  base32: ">=1.0.1 <2.0.0"

dev_dependencies:
  test: any
